- name: Main Ansible playbook.
  hosts: localhost
  become: true

  vars_files:
    - HOSTS_VARS

  tasks:

    # ensure basic packages are installed
    - include_tasks: tasks/packages.yml

    # download the dotfiles repo
    - name: Ensure dotfiles repo is present on the system.
      become_user: "{{ user }}"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_dest }}"
        version: "{{ dotfiles_repo_version }}"

    # zsh setup
    - include_tasks: tasks/zsh.yml

    # pyenv setup
    # - include_tasks: tasks/pyenv.yml

    # gitconfig setup
    - include_tasks: tasks/gitconfig.yml

    # tmux setup
    - include_tasks: tasks/tmux.yml

    # neovim setup
    - include_tasks: tasks/neovim.yml
