- name: Main Ansible playbook.
  hosts: localhost
  become: true

  vars:

    # just a sanity-check
    user: "{{ lookup('env', 'USER') | default('alex', true) }}"
    home: "{{ lookup('env', 'HOME') | default('/home/alex/', true) }}"

    # xdg base dirs spec (these will be sourced anyway later in .zshrc, but we need them now)
    xdg_config: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(home + '/.config', true) }}"
    xdg_data: "{{ lookup('env', 'XDG_DATA_HOME') | default(home + '/.local/share', true) }}"
    xdg_cache: "{{ lookup('env', 'XDG_CACHE_HOME') | default(home + '/.cache', true) }}"

    # the path to the pyenv executable
    pyenv_pip3_path: "/home/{{ user }}/.pyenv/versions/3.9.5/bin/pip3"

    packages_to_install_arch:
      - base-devel
      - openssl
      - xz
      - zlib
      - curl
      - stow
      - nodejs-lts-fermium
      - pyenv
      - fzf
      - tree-sitter
      - luajit
      - ccls

    packages_to_install_ubuntu:
      - build-essential
      - curl
      - stow
      - nodejs
      - fzf
      - luajit
      - ccls

  tasks:

    # default user, groups setup
    - include: tasks/user.yml

    # basic package installs
    - include: tasks/packages.yml

    # download the dotfiles repo
    - name: Ensure dotfiles repo is present on the system.
      become_user: "{{ user }}"
      git:
        repo: "https://github.com/alexghergh/dotfiles"
        dest: "{{ home }}/.dotfiles"

    # zsh setup
    - include: tasks/zsh.yml

    # oh-my-zsh setup
    - include: tasks/oh-my-zsh.yml

    # pyenv setup
    - include: tasks/pyenv.yml

    # gitconfig setup
    - include: tasks/gitconfig.yml

    # tmux setup
    - include: tasks/tmux.yml

    # neovim setup
    - include: tasks/neovim.yml
