- name: Main Ansible playbook.
  hosts: localhost
  become: true

  vars_files:
    - HOSTS_VARS

  vars_prompt:

    - name: password
      prompt: Password -> 
      private: yes

    - name: passwordsalt
      prompt: Password salt -> 
      private: yes

  tasks:

    # default user, groups, password setup
    - include: tasks/user.yml

    # basic package installs
    - include: tasks/packages.yml

    # download the dotfiles repo
    - name: Ensure dotfiles repo is present on the system.
      become_user: "{{ user }}"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_repo_dest }}"
        version: "{{ dotfiles_repo_version }}"

    # zsh setup
    - include: tasks/zsh.yml

    # pyenv setup
    # - include: tasks/pyenv.yml

    # gitconfig setup
    - include: tasks/gitconfig.yml

    # tmux setup
    - include: tasks/tmux.yml

    # neovim setup
    - include: tasks/neovim.yml
