# Arch Linux
- name: Ensure the git package is installed (Archlinux).
  pacman:
    name: git
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Ensure the git package is installed (Ubuntu / Debian).
  apt:
    name: git
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure the git config dir doesn't exist already.
  file:
    path: "{{ git_config_dir }}"
    state: absent

- name: Stow the git configs.
  become_user: "{{ user }}"
  command:
    cmd: "{{ git_stow_cmd }}"
    chdir: "{{ dotfiles_dir }}"
