# Arch Linux
- name: Ensure the git package is installed (Archlinux).
  pacman:
    name: git
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Ensure the git package is installed (Ubuntu / Debian).
  apt:
    name: git
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure gitconfig does not exist already.
  file:
    path: "{{ xdg_config }}/git"
    state: absent

- name: Stow the git configs.
  become_user: "{{ user }}"
  command:
    cmd: 'stow --restow --verbose --dir="{{ home }}/.dotfiles" --target="{{ home }}" git'
    chdir: "{{ home }}/.dotfiles"
