- name: Ensure gitconfig does not exist already.
  file:
    path: "{{ xdg_config }}/git"
    state: absent

- name: Stow the git configs.
  become_user: "{{ user }}"
  command:
    cmd: 'stow --restow --verbose --dir="{{ home }}/.dotfiles" --target="{{ home }}" git'
    chdir: "{{ home }}/.dotfiles"
