- name: Ensure .gitconfig file does not exist already.
  file:
    path: "{{ home }}/.gitconfig"
    state: absent

- name: Stow the git configs.
  command:
    cmd: 'stow --restow --verbose --dir="{{ home }}/.dotfiles" --target="{{ home }}" git'
    chdir: "{{ home }}/.dotfiles"
