# Arch Linux
- name: Update and upgrade the system (Archlinux). Equivalent to "pacman -Syu".
  pacman:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Archlinux"

- name: Ensure basic utilities are installed (Archlinux).
  pacman:
    name: "{{ packages_to_install_arch }}"
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Update and upgrade the system (Ubuntu / Debian). Equivalent to "apt update && apt upgrade".
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure basic utilities are installed (Ubuntu / Debian).
  apt:
    name: "{{ packages_to_install_ubuntu }}"
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Asahi Linux (Fedora Remix)
- name: Update and upgrade the system (Asahi Fedora Linux). Equivalent to "dnf upgrade".
  dnf:
    update_cache: yes
    name: '*'
    state: latest
  when: ansible_distribution == "Fedora"

- name: Ensure basic utilities are installed (Asahi Fedora Linux).
  dnf:
    name: "{{ packages_to_install_asahi }}"
    state: latest
  when: ansible_distribution == "Fedora"
