# Arch Linux
- name: Ensure the tmux package is installed (Archlinux).
  pacman:
    name: tmux
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Ensure tmux dependencies are installed (Ubuntu / Debian).
  apt:
    name: "{{ tmux_dependencies_ubuntu }}"
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Ensure the tmux git repo is present (Ubuntu / Debian).
  become_user: "{{ user }}"
  git:
    repo: "{{ tmux_repo }}"
    dest: "{{ tmux_repo_dest }}"
    version: "{{ tmux_repo_version }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Ensure the repo is clean of config files (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "{{ tmux_clean_repo_cmd }}"
    chdir: "{{ tmux_repo_dest }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part I (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "{{ tmux_install_cmd_1 }}"
    chdir: "{{ tmux_repo_dest }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part II (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "{{ tmux_install_cmd_2 }}"
    chdir: "{{ tmux_repo_dest }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# # Ubuntu / Debian
- name: Configure and install tmux part III (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "{{ tmux_install_cmd_3 }}"
    chdir: "{{ tmux_repo_dest }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part II (Ubuntu / Debian).
  command:
    cmd: "{{ tmux_install_cmd_4 }}"
    chdir: "{{ tmux_repo_dest }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure the tmux config dir doesn't exist already.
  file:
    path: "{{ tmux_config_dir }}"
    state: absent

- name: Stow the tmux configs.
  become_user: "{{ user }}"
  command:
    cmd: "{{ tmux_stow_cmd }}"
    chdir: "{{ dotfiles_dir }}"

- name: Ensure tmux plugin manager is installed.
  become_user: "{{ user }}"
  git:
    repo: "{{ tmux_plugin_manager_repo }}"
    dest: "{{ tmux_plugin_manager_repo_dest }}"

- name: Ensure the other tmux plugins are installed.
  become_user: "{{ user }}"
  shell:
    cmd: "{{ tmux_plugins_install_cmd }}"
    chdir: "{{ tmux_plugins_installer_path }}"
