- name: Ensure ~/.config/tmux/ doesn't exist already.
  file:
    path: "{{ xdg_config }}/tmux/"
    state: absent

# Arch Linux
- name: Ensure the tmux package is installed (Archlinux).
  pacman:
    name: tmux
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Ensure tmux dependencies are installed (Ubuntu / Debian).
  apt:
    name: [ 'libevent-dev', 'ncurses-dev', 'build-essential', 'bison', 'pkg-config', 'autoconf', 'automake' ]
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Ensure the tmux git repo is present (Ubuntu / Debian).
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/tmux/tmux"
    dest: "{{ home }}/tmux-git"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part I (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "sh autogen.sh"
    chdir: "{{ home }}/tmux-git"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part II (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "./configure"
    chdir: "{{ home }}/tmux-git"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part III (Ubuntu / Debian).
  become_user: "{{ user }}"
  command:
    cmd: "make"
    chdir: "{{ home }}/tmux-git"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

# Ubuntu / Debian
- name: Configure and install tmux part IV (Ubuntu / Debian).
  command:
    cmd: "make install"
    chdir: "{{ home }}/tmux-git"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Stow the tmux configs.
  become_user: "{{ user }}"
  command:
    cmd: 'stow --restow --verbose --dir="{{ home }}/.dotfiles" --target="{{ home }}" tmux'
    chdir: "{{ home }}/.dotfiles"

- name: Ensure tmux plugin manager is installed.
  become_user: "{{ user }}"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ xdg_config }}/tmux/plugins/tpm"

- name: Ensure the other tmux plugins are installed.
  become_user: "{{ user }}"
  command:
    cmd: "./install_plugins.sh"
    chdir: "{{ xdg_config }}/tmux/plugins/tpm/scripts"
