- name: Ensure the group exists for the user.
  group:
    name: "{{ user }}"
    state: present

- name: Ensure user exists and has the correct home and password set.
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    group: "{{ user }}"
    password: "{{ password | password_hash('sha512', passwordsalt) }}"
    update_password: on_create
    state: present

# Arch Linux
- name: Ensure user has the correct groups (Arch Linux).
  user:
    name: "{{ user }}"
    append: yes
    groups: []
  when: ansible_distribution == "Archlinux"

# Ubuntu
- name: Ensure user has the correct groups (Ubuntu).
  user:
    name: "{{ user }}"
    append: yes
    groups: [ 'adm', 'cdrom', 'sudo', 'dip', 'plugdev', 'lpadmin', 'lxd', 'sambashare' ]
  when: ansible_distribution == "Ubuntu"
