- name: Ensure the group exists for the user.
  group:
    name: "{{ user }}"
    state: present

# NOTE: This will fail when trying to execute the ansible script as the
# same user we're trying to operate on.
#
# Ideally, this should either be executed as another user, or should be
# executed from the root account.
#
# For more information, see 'man usermod' (CAVEATS section).
#
# The salt should be at least 16 bytes of random data from /dev/urandom
- name: Ensure user exists and has the correct home and password set.
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    group: "{{ user }}"
    password: "{{ password | password_hash('sha512', passwordsalt) }}"
    update_password: on_create
    state: present
  ignore_errors: yes

# Arch Linux
# TODO: see what groups a user should be in
- name: Ensure user has the correct groups (Arch Linux).
  user:
    name: "{{ user }}"
    append: yes
    groups: "{{ user_groups_arch }}"
  when: ansible_distribution == "Archlinux"

# Ubuntu
- name: Ensure user has the correct groups (Ubuntu).
  user:
    name: "{{ user }}"
    append: yes
    groups: "{{ user_groups_ubuntu }}"
  when: ansible_distribution == "Ubuntu"
