# Arch Linux
- name: Ensure the zsh package is installed (Archlinux).
  pacman:
    name: zsh
    state: latest
  when: ansible_distribution == "Archlinux"

# Ubuntu / Debian
- name: Ensure the zsh package is installed (Ubuntu / Debian).
  apt:
    name: zsh
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure the zsh config dir doesn't exist already.
  file:
    path: "{{ zsh_config_dir }}"
    state: absent

- name: Stow the zsh configs.
  become_user: "{{ user }}"
  command:
    cmd: "{{ zsh_stow_cmd }}"
    chdir: "{{ dotfiles_dir }}"

- name: Ensure the user has the correct shell (zsh).
  user:
    name: "{{ user }}"
    shell: /bin/zsh
    state: present
